use crowsi_certificate_manager::VerifiedCertificateExecutionAuthorizationV2 as Manager;
use crowsi_control_contracts::VerifiedCertificateExecutionAuthorizationV2 as Contract;

use super::{
    contract_action, contract_approval_assurance, contract_approval_method, contract_operation,
};

pub fn adapt_contract_authorization(value: Contract) -> Option<Manager> {
    let operation_binding = contract_operation(&value)?;
    Some(Manager {
        authorization_id: value.authorization_id,
        jti: value.jti,
        operation_id: value.operation_id,
        operation_binding,
        lease_digest_sha256: value.lease_digest_sha256,
        command_digest_sha256: value.command_digest_sha256,
        action: contract_action(value.action),
        issuer: value.issuer,
        audience: value.audience,
        signature_key_id: value.signature_key_id,
        signature_key_version: value.signature_key_version,
        signature_public_key_spki_sha256: value.signature_public_key_spki_sha256,
        signature_algorithm: value.signature_algorithm,
        signature_key_purpose: value.signature_key_purpose,
        trust_revision: value.trust_revision,
        channel: value.channel,
        approval_id: value.approval_id,
        approval_evidence_digest_sha256: value.approval_evidence_digest_sha256,
        approval_method: value.approval_method.map(contract_approval_method),
        approval_assurance: value.approval_assurance.map(contract_approval_assurance),
        approval_verified_at_epoch_s: value.approval_verified_at_epoch_s,
        approval_issued_at_epoch_s: value.approval_issued_at_epoch_s,
        approval_expires_at_epoch_s: value.approval_expires_at_epoch_s,
        security_domain: value.security_domain,
        deployment_id: value.deployment_id,
        release_id: value.release_id,
        release_digest_sha256: value.release_digest_sha256,
        checkpoint_id: value.checkpoint_id,
        checkpoint_digest_sha256: value.checkpoint_digest_sha256,
        checkpoint_sequence: value.checkpoint_sequence,
        deployment_provenance_ref: value.deployment_provenance_ref,
        pa_reservation_id: value.pa_reservation_id,
        policy_id: value.policy_id,
        policy_digest_sha256: value.policy_digest_sha256,
        decision_id: value.decision_id,
        decision_digest_sha256: value.decision_digest_sha256,
        grant_id: value.grant_id,
        grant_digest_sha256: value.grant_digest_sha256,
        pairwise_subject: value.pairwise_subject,
        requester_pairwise_subject: value.requester_pairwise_subject,
        approver_pairwise_subject: value.approver_pairwise_subject,
        requester_profile: value.requester_profile,
        requester_device: value.requester_device,
        requester_actor: value.requester_actor,
        requester_proof_key_ref: value.requester_proof_key_ref,
        approver_profile: value.approver_profile,
        approver_device: value.approver_device,
        approver_actor: value.approver_actor,
        approver_proof_key_ref: value.approver_proof_key_ref,
        workload: value.workload,
        previous_identity_revocation_epoch: value.previous_identity_revocation_epoch,
        identity_revocation_epoch: value.identity_revocation_epoch,
        previous_lifecycle_revocation_epoch: value.previous_lifecycle_revocation_epoch,
        lifecycle_revocation_epoch: value.lifecycle_revocation_epoch,
        identity_revocation_snapshot_id: value.revocation_snapshot_id,
        identity_revocation_snapshot_digest_sha256: value.revocation_snapshot_digest_sha256,
        identity_revocation_snapshot_epoch: value.revocation_snapshot_epoch,
        identity_revocation_snapshot_verified_at_epoch_s: value
            .revocation_snapshot_verified_at_epoch_s,
        authoritative_identity_revocation_snapshot: value.authoritative_revocation_snapshot,
        service_id: value.service_id,
        provider: value.provider,
        target_resource_id: value.target_resource_id,
        target_resource_normalizer_id: value.target_resource_normalizer_id,
        target_resource_normalizer_version: value.target_resource_normalizer_version,
        target_resource_normalization_digest_sha256: value
            .target_resource_normalization_digest_sha256,
        target_resource_normalization_verified: value.target_resource_normalization_verified,
        unknown_evidence_digest_sha256: value.unknown_evidence_digest_sha256,
        previous_fence: value.previous_fence,
        current_fence: value.current_fence,
        expected_resource_version: value.expected_resource_version,
        issued_at_epoch_s: value.issued_at_epoch_s,
        expires_at_epoch_s: value.expires_at_epoch_s,
        one_use: value.one_use,
        signature_verified: value.signature_verified,
    })
}
